

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BinaryGaming
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class BinaryGamingDataContainer : DbContext
{
    public BinaryGamingDataContainer()
        : base("name=BinaryGamingDataContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Members> Members { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<MembershipTypes> MembershipTypes { get; set; }

    public virtual DbSet<TransactionTypes> TransactionTypes { get; set; }

    public virtual DbSet<CommitteePositions> CommitteePositions { get; set; }

    public virtual DbSet<Committee> Committees { get; set; }

    public virtual DbSet<LoginLog> LoginLogs { get; set; }

    public virtual DbSet<Invoices> Invoices { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }


    public virtual ObjectResult<GetMatchedMemberList_Result> GetMatchedMemberList(Nullable<int> requestedPage, Nullable<int> rowsPerPage, string searchString)
    {

        var requestedPageParameter = requestedPage.HasValue ?
            new ObjectParameter("RequestedPage", requestedPage) :
            new ObjectParameter("RequestedPage", typeof(int));


        var rowsPerPageParameter = rowsPerPage.HasValue ?
            new ObjectParameter("RowsPerPage", rowsPerPage) :
            new ObjectParameter("RowsPerPage", typeof(int));


        var searchStringParameter = searchString != null ?
            new ObjectParameter("SearchString", searchString) :
            new ObjectParameter("SearchString", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMatchedMemberList_Result>("GetMatchedMemberList", requestedPageParameter, rowsPerPageParameter, searchStringParameter);
    }


    public virtual ObjectResult<Nullable<int>> GetMatchedMemberListCount(string searchString)
    {

        var searchStringParameter = searchString != null ?
            new ObjectParameter("SearchString", searchString) :
            new ObjectParameter("SearchString", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetMatchedMemberListCount", searchStringParameter);
    }

}

}

