
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BinaryGaming
{

using System;
    using System.Collections.Generic;
    
public partial class Invoices
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Invoices()
    {

        this.Transactions = new HashSet<Transaction>();

    }


    public int Id { get; set; }

    public Nullable<int> MembersId { get; set; }

    public System.DateTime Date { get; set; }

    public string MembershipType { get; set; }

    public decimal Amount { get; set; }

    public decimal Outstanding { get; set; }



    public virtual Members Member { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transaction> Transactions { get; set; }

}

}
