
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BinaryGaming
{

using System;
    using System.Collections.Generic;
    
public partial class Members
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Members()
    {

        this.Mobile = "\"\"";

        this.FinancialYN = false;

        this.DiscordId = 0;

        this.Transactions = new HashSet<Transaction>();

        this.Committees = new HashSet<Committee>();

        this.LoginLogs = new HashSet<LoginLog>();

        this.Invoices = new HashSet<Invoices>();

    }


    public int Id { get; set; }

    public string Surname { get; set; }

    public string FirstName { get; set; }

    public string MiddleNames { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Suburb { get; set; }

    public string State { get; set; }

    public string Postcode { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public System.DateTime DateJoined { get; set; }

    public bool FinancialYN { get; set; }

    public int MembershipTypesId { get; set; }

    public System.DateTime MembershipExpiry { get; set; }

    public string DiscordName { get; set; }

    public Nullable<long> DiscordId { get; set; }

    public System.DateTime LastLoggedIn { get; set; }

    public string AspNetUserId { get; set; }



    public virtual MembershipTypes MembershipTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transaction> Transactions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Committee> Committees { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LoginLog> LoginLogs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoices> Invoices { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }

}

}
