
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BinaryGaming
{

using System;
    using System.Collections.Generic;
    
public partial class Transaction
{

    public int Id { get; set; }

    public System.DateTime TransactionDate { get; set; }

    public decimal Amount { get; set; }

    public int TransactionTypesId { get; set; }

    public int MembersId { get; set; }

    public int InvoicesId { get; set; }



    public virtual TransactionTypes TransactionType { get; set; }

    public virtual Members Member { get; set; }

    public virtual Invoices Invoice { get; set; }

}

}
