// <auto-generated />
namespace BinaryGaming.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig20170612a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig20170612a));
        
        string IMigrationMetadata.Id
        {
            get { return "201706120651514_mig20170612a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
